export const Now = [
  {
    title: "취향의 밤",
    type: "공연",
    place: "대림미술관",
    for: "성인",
    des: "오직 당신만을 위해 준비된 대림미술관의 취향저격 큐레이션",
    src: "../img/program-2024-1.jpg",
  },
  {
    title: "크리에이터의 발상법",
    type: "교육",
    place: "대림미술관",
    for: "청소년",
    des: "크리에이터 MSCHF의 창의적 발상법을 직접 경험해보는 감상 기반 청소년 진로탐색 프로그램",
    src: "../img/program-2024-2.jpg",
  },
  {
    title: "스페셜 필드트립",
    type: "공연",
    place: "대림미술관",
    for: "성인",
    des: "영감과 아이디어를 얻고 싶은 직장인들을 위한 프라이빗 단체 투어",
    src: "../img/program-2024-3.jpg",
  },
  {
    title: "정규 투어",
    type: "공연",
    place: "대림미술관",
    for: "관람객",
    des: "<MSCHF:NOTHING IS SACRED> 전시 관람객이라면 누구나 참여할 수 있는 정규 투어",
    src: "../img/program-2024-4.jpg",
  },
];

export const Past = [
  {
    year: 2022,
    item: [
      {
        title: "정규투어",
        type: "전시 해설",
        place: "디뮤지엄",
        for: "관람객",
        des: "<어쨌든,사랑 : Romantic Days> 전시 관람객이면 누구나 참여할 수 있는 정규 투어",
        src: "../img/program-2022-1.jpg",
      },
      {
        title: "온라인 진로특강",
        type: "교육",
        place: "디뮤지엄",
        for: "대학생",
        des: "문화예술 분야 진로를 희망하는 대학(원)생들을 위한 미술관 진로탐색 교육",
        src: "../img/program-2022-2.png",
      },
      {
        title: "해피투게더",
        type: "교육",
        place: "디뮤지엄",
        for: "청소년",
        des: "누구나, 차별없이 문화예술을 경험할 수 있도록 대림문화재단이 진행하는 문화소외 청소년 대상 예술 교육 프로그램",
        src: "../img/program-2022-3.png",
      },
      {
        title: "키즈워크룸 : 애니메이터 프로젝트",
        type: "교육",
        place: "디뮤지엄",
        for: "어린이",
        des: "움직이는 그림을 만드는 우리는, 키즈 애니메이터! 과학과 움직임의 원리가 더해진 무빙 프로젝터로 2D 애니메이션을 제작하는 문제해결 중심 융복합 교육",
        src: "../img/program-2022-4.jpg",
      },
    ],
  },
  {
    year: 2020,
    item: [
      {
        title: "사운드 큐브 (Sound Cube)",
        type: "교육",
        place: "디뮤지엄",
        for: "청소년",
        des: "우리 주변엔 어떤 소리들이 있을까? 작가는 이 소리들로 어떻게 작품을 만들었을까? 나는 어떤 작품을 만들 수 있을까? 질문에 답을 찾아가며 새롭게 발견하는 '소리'의 의미! 일상의 소리에 기술과 감성을 더한 나만의 예술작품 제작하기",
        src: "../img/program-2020-1.jpg",
      },
      {
        title: "사운드 메이커",
        type: "교육",
        place: "디뮤지엄",
        for: "어린이",
        des: "소리로 예술 작품을 만들 수 있을까? 새로운 표션 재료로서 '소리'를 만나고, 사운드 머신 키트를 활용해 나의 기억과 감정을 담은 사운드 아트 작품 제작하기",
        src: "../img/program-2020-2.jpg",
      },
    ],
  },
  {
    year: 2019,
    item: [
      {
        title: "전시 연계 교사 워크숍_초등",
        type: "교육",
        place: "대림미술관",
        for: "교사",
        des: "상상과 이야기가 가득한 하이메 아욘의 작품들이 가진 교육적 가치를 짚어보고, 작품들을 쉽고 재미있게 감상해 볼 수 있는 다각적 감상법을 제시",
        src: "../img/program-2019-1.jpg",
      },
      {
        title: "디자인톡 (Design Talk)",
        type: "교육",
        place: "대림미술관",
        for: "성인",
        des: "전문 디자이너의 시각으로 새롭게 해석한 Jaime Hayon의 이야기",
        src: "../img/program-2019-2.jpg",
      },
      {
        title: "Museum Palette",
        type: "교육",
        place: "디뮤지엄",
        for: "성인",
        des: "수채화로 그리는 보태니컬 드로잉",
        src: "../img/program-2019-3.jpg",
      },
      {
        title: "해피 칠드런 : 창작 (키즈 시어터)",
        type: "교육",
        place: "대림미술관",
        for: "어린이",
        des: "불이 꺼지면, 작품들이 숨겨진 사연을 풀어 놓는다! 감상활동을 바탕으로 작품들이 가진 이야기를 상상해보고 그림자 극으로 표현해보는 융복합 예술교육",
        src: "../img/program-2019-4.jpg",
      },
      {
        title: "교사 초청 워크숍",
        type: "교육",
        place: "디뮤지엄",
        for: "교사",
        des: "미술관 교육과 Visual Thinking Strategies 접목한 전문가의 강연과 사진, 영상, 설치 작품을 통해 시각적 문해력을 향상시킬 수 있는 효과적인 감상 교육법 공유",
        src: "../img/program-2019-5.jpg",
      },
    ],
  },
  {
    year: 2018,
    item: [
      {
        title: "미술관 아카데미 : 포토그래피 인사이트 워크숍1",
        type: "교육",
        place: "대림미술관",
        for: "성인",
        des: "Chapter 1. 스트리트 사진의 세계 with 구영준 포토그래퍼",
        src: "../img/program-2018-1.jpg",
      },
      {
        title: "미술관 아카데미 : 포토그래피 인사이트 워크숍2",
        type: "교육",
        place: "대림미술관",
        for: "성인",
        des: "Chapter 2. 패션 화보의 세계",
        src: "../img/program-2018-2.jpg",
      },
      {
        title: "아트앤핏 : 발레",
        type: "교육",
        place: "디뮤지엄",
        for: "성인",
        des: "5월의 햇살 속 피어나는 꽃처럼 섬세한 움직임, 발레",
        src: "../img/program-2018-3.jpg",
      },
      {
        title: "셀피, 오늘 나의 자화상",
        type: "교육",
        place: "대림미술관",
        for: "청소년",
        des: "오늘의 나를 사진으로 표현한다면? 사진으로 자신을 탐구했던 작가처럼 오늘 나의 감정과 생각을 셀피(Selfie) 속에 담자보는 감상 + 창작활동",
        src: "../img/program-2018-4.jpg",
      },
      {
        title: "마음날씨연구소",
        type: "교육",
        place: "디뮤지엄",
        for: "어린이",
        des: "날씨 박스 안에 입체적으로 표현하는 나의 기분, 감정, 추억을 담은 날씨 이야기",
        src: "../img/program-2018-5.jpg",
      },
    ],
  },
];
