export const FrontInfo = [
  {
    sort: "poster",
    title: "포스터에 담긴 미스치프",
    des: "미스치프 작가진은 길거리부터 매일 먹고 마시는 식음료를 비롯한우리 주변 모든 곳에 영향력을 행사합니다. 그들의 생동감 넘치는 묘사력은 전시 포스터를 통해 특유의 존재감을 보여줍니다. 창의적이고 독특한 아이디어가 담긴 전시 포스터를 소장해보세요.",
    img: [
      {
        src: "../img/shop-poster8.jpg",
        alt: "[미스치프] A3 아트워크 포스터 세트",
      },

      {
        src: "../img/shop-poster2.jpg",
        alt: "[미스치프] 전시 포스터 02",
      },
      {
        src: "../img/shop-poster3.jpg",
        alt: "[미스치프] 전시 포스터 03",
      },
      {
        src: "../img/shop-poster6.jpg",
        alt: "[미스치프] 전시 포스터 06",
      },
    ],
    btn: "다른 포스터 상품 보기",
  },
  {
    sort: "stationary",
    title: "일상을 예술로",
    des: "일상 속에서 매일 만지는 사소한 물건들을 고르는 것은 아주 중요하죠.미스치프의 재치있고 각적인 감성을 담은 박스 테이프, 공책, 키링 세트 등과같은 다양한 소품들로 일상을 예술로 만들어보세요.",
    img: [
      {
        src: "../img/shop-boxTape.jpg",
        alt: "[미스치프] 박스테이프 2종",
      },
      {
        src: "../img/shop-note.jpg",
        alt: "[미스치프] 그래픽 노트 5종",
      },
      {
        src: "../img/shop-keyring.jpg",
        alt: "[미스치프] 아트워크 키링 엽서 세트",
      },
      {
        src: "../img/shop-stickerM.jpg",
        alt: "[미스치프] 리무버블 스티커 M",
      },
    ],
    btn: "다른 문구 상품 보기",
  },
];

export const ShopInfo = [
  {
    id: "all",
    item: [],
  },
  {
    id: "poster",
    item: [
      {
        img: "../img/shop-poster1.jpg",
        bgColor: "#EAECEB",
        name: "[미스치프] 전시 포스터 01",
        place: "대림미술관",
        price: "13,000원",
        rate: "50%",
        total: "6,500원",
      },
      {
        bgColor: "#EAECEB",
        img: "../img/shop-poster2.jpg",
        name: "[미스치프] 전시 포스터 02",
        place: "대림미술관",
        price: "13,000원",
        rate: "50%",
        total: "6,500원",
      },
      {
        bgColor: "#EAECEB",
        img: "../img/shop-poster3.jpg",
        name: "[미스치프] 전시 포스터 03",
        place: "대림미술관",
        price: "13,000원",
        rate: "50%",
        total: "6,500원",
      },
      {
        bgColor: "#EAECEB",
        img: "../img/shop-poster4.jpg",
        name: "[미스치프] 전시 포스터 04",
        place: "대림미술관",
        price: "13,000원",
        rate: "50%",
        total: "6,500원",
      },
      {
        bgColor: "#EAECEB",
        img: "../img/shop-poster5.jpg",
        name: "[미스치프] 전시 포스터 05",
        place: "대림미술관",
        price: "13,000원",
        rate: "50%",
        total: "6,500원",
      },
      {
        img: "../img/shop-poster6.jpg",
        bgColor: "#EAECEB",
        name: "[미스치프] 전시 포스터 06",
        place: "대림미술관",
        price: "13,000원",
        rate: "50%",
        total: "6,500원",
      },
      {
        img: "../img/shop-poster7.jpg",
        bgColor: "#EAECEB",
        name: "[미스치프] 전시 포스터 07",
        place: "대림미술관",
        price: "13,000원",
        rate: "50%",
        total: "6,500원",
      },
      {
        img: "../img/shop-poster8.jpg",
        bgColor: "#EAECEB",
        name: "[미스치프] A3 아트워크 포스터 세트",
        place: "대림미술관",
        price: "79,000원",
        rate: "35%",
        total: "51,350원",
      },
    ],
  },
  {
    id: "book",
    item: [
      {
        img: "../img/shop-book.jpg",
        bgColor: "#DF0429",
        name: "[미스치프] 전시 도록",
        place: "대림미술관",
        price: "49,000원",
        rate: "10%",
        total: "38,700원",
      },
    ],
  },
  {
    id: "stationary",
    item: [
      {
        bgColor: "#EAECEB",
        img: "../img/shop-boxTape.jpg",
        name: "[미스치프] 박스테이프 2종",
        place: "대림미술관",
        total: "7,000원",
      },
      {
        bgColor: "#EAECEB",
        img: "../img/shop-note.jpg",
        name: "[미스치프] 그래픽 노트 5종",
        place: "대림미술관",
        price: "7000원",
        rate: "35%",
        total: "4,550원",
      },
      {
        img: "../img/shop-postCard1.jpg",
        bgColor: "#000",
        name: "[미스치프] 엽서 유광 5종",
        place: "대림미술관",
        price: "3,500원",
        rate: "50%",
        total: "1,750 원",
      },
      {
        img: "../img/shop-postCard2.jpg",
        bgColor: "#000",
        name: "[미스치프] 엽서 무광 5종",
        place: "대림미술관",
        price: "3,500원",
        rate: "50%",
        total: "1,750 원",
      },
      {
        bgColor: "#EAECEB",
        img: "../img/shop-keyring.jpg",
        name: "[미스치프] 아트워크 키링 엽서 세트",
        place: "대림미술관",
        total: "18,000 원",
      },
      {
        img: "../img/shop-stickerHolo.jpg",
        bgColor: "#EAECEB",
        name: "[미스치프] 홀로그램 리무버블 스티커",
        place: "대림미술관",
        price: "3,200원",
        rate: "40%",
        total: "1,920 원",
      },
      {
        bgColor: "#EAECEB",
        img: "../img/shop-stickerM.jpg",
        name: "[미스치프] 리무버블 스티커 M",
        place: "대림미술관",
        price: "2,500원",
        rate: "50%",
        total: "1,250 원",
      },
      {
        img: "../img/shop-stickerL.jpg",
        bgColor: "#EAECEB",
        name: "[미스치프] 리무버블 스티커 L",
        place: "대림미술관",
        price: "2,800원",
        rate: "50%",
        total: "1,400 원",
      },
    ],
  },
  {
    id: "living",
    item: [
      {
        img: "../img/shop-pin.jpg",
        bgColor: "#DF0429",
        name: "[미스치프] 핀 뱃지 세트",
        place: "대림미술관",
        total: "47,000원",
      },
    ],
  },
];
